-- Run this in your Supabase SQL Editor to add the missing columns for the new Invoice PDF features

-- Add fields to sales table
ALTER TABLE public.sales 
ADD COLUMN IF NOT EXISTS customer_phone TEXT,
ADD COLUMN IF NOT EXISTS customer_email TEXT,
ADD COLUMN IF NOT EXISTS customer_gstin TEXT,
ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cgst DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS sgst DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS igst DECIMAL(10,2) DEFAULT 0;

-- Add fields to purchases table
ALTER TABLE public.purchases 
ADD COLUMN IF NOT EXISTS vendor_phone TEXT,
ADD COLUMN IF NOT EXISTS vendor_email TEXT,
ADD COLUMN IF NOT EXISTS vendor_gstin TEXT,
ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cgst DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS sgst DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS igst DECIMAL(10,2) DEFAULT 0;
