import json
from pathlib import Path

def resolve_type(prop: dict, required: bool = True) -> str:
    # Handle $ref
    if "$ref" in prop:
        ref_name = prop["$ref"].split("/")[-1]
        return ref_name
    
    # Handle anyOf / allOf / oneOf
    if "anyOf" in prop:
        sub_types = [resolve_type(sub) for sub in prop["anyOf"] if sub.get("type") != "null"]
        if not sub_types:
            sub_types = ["any"]
        base = " | ".join(sub_types)
        if any(sub.get("type") == "null" for sub in prop["anyOf"]):
            base += " | null"
        return base

    t = prop.get("type")
    if t == "string":
        if "enum" in prop:
            return " | ".join(f'"{v}"' for v in prop["enum"])
        return "string"
    elif t in ("integer", "number", "float"):
        return "number"
    elif t == "boolean":
        return "boolean"
    elif t == "array":
        item_schema = prop.get("items", {})
        item_type = resolve_type(item_schema)
        if " | " in item_type:
            return f"({item_type})[]"
        return f"{item_type}[]"
    elif t == "object":
        add_props = prop.get("additionalProperties")
        if isinstance(add_props, dict):
            val_type = resolve_type(add_props)
            return f"Record<string, {val_type}>"
        return "Record<string, any>"
    
    return "any"

def generate_typescript():
    spec_path = Path(__file__).resolve().parent / "openapi.json"
    with open(spec_path, "r", encoding="utf-8") as f:
        spec = json.load(f)

    schemas = spec.get("components", {}).get("schemas", {})
    lines = [
        "/**",
        " * Auto-generated TypeScript definitions from FastAPI OpenAPI Schema.",
        " * Generated by @rupaybill/api-types pipeline.",
        " * DO NOT EDIT DIRECTLY.",
        " */",
        "",
    ]

    for name, schema in sorted(schemas.items()):
        description = schema.get("description")
        if description:
            lines.append(f"/** {description} */")
        
        # Check if enum-only schema
        if "enum" in schema:
            vals = " | ".join(f'"{v}"' for v in schema["enum"])
            lines.append(f"export type {name} = {vals};")
            lines.append("")
            continue

        props = schema.get("properties", {})
        required_fields = set(schema.get("required", []))
        
        lines.append(f"export interface {name} {{")
        for prop_name, prop_def in sorted(props.items()):
            is_req = prop_name in required_fields
            q = "" if is_req else "?"
            ts_type = resolve_type(prop_def, is_req)
            doc = prop_def.get("description") or prop_def.get("title")
            if doc and doc != prop_name:
                lines.append(f"  /** {doc} */")
            lines.append(f"  {prop_name}{q}: {ts_type};")
        lines.append("}")
        lines.append("")

    out_path = Path(__file__).resolve().parent / "src" / "generated.ts"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated {len(schemas)} TypeScript interfaces in {out_path}")

if __name__ == "__main__":
    generate_typescript()
