import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

export interface PartyReportItem {
    name: string;
    totalSales: number;
    totalPurchases: number;
    netBalance: number;
    salesCount: number;
    purchasesCount: number;
}

const sanitizeText = (text: string) => {
    return text.replace(/[^\x00-\x7F]/g, "");
};

const formatCurrencySafe = (amount: number | string) => {
    const num = Number(amount);
    if (isNaN(num)) return "0.00";
    return `Rs. ${num.toFixed(2)}`;
};

export const exportPartyReportPDF = (
    data: PartyReportItem[],
    businessDetails?: { name: string; address?: string; phone?: string; gst?: string; }
) => {
    try {
        if (!data || data.length === 0) {
            alert("No party data to export.");
            return;
        }

        const doc = new jsPDF();

        // --- Header ---
        doc.setFontSize(24);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(33, 33, 33);
        doc.text("PARTY REPORT", 196, 20, { align: "right" });

        // Brand / Business Details
        if (businessDetails?.name) {
            doc.setFontSize(18);
            doc.setTextColor(37, 99, 235);
            doc.text(sanitizeText(businessDetails.name), 14, 20);

            doc.setFontSize(10);
            doc.setTextColor(80, 80, 80);
            doc.setFont("helvetica", "normal");

            let yPos = 26;
            if (businessDetails.address) {
                const splitAddress = doc.splitTextToSize(sanitizeText(businessDetails.address), 100);
                doc.text(splitAddress, 14, yPos);
                yPos += (splitAddress.length * 4) + 2;
            }

            if (businessDetails.phone) {
                doc.text(`Phone: ${sanitizeText(businessDetails.phone)}`, 14, yPos);
                yPos += 5;
            }

            if (businessDetails.gst) {
                doc.text(`GST: ${sanitizeText(businessDetails.gst)}`, 14, yPos);
            }
        } else {
            doc.setFontSize(18);
            doc.setTextColor(37, 99, 235);
            doc.text("FinFlow Business", 14, 20);
        }

        // --- Line ---
        const headerBottom = 55;
        doc.setLineWidth(0.5);
        doc.setDrawColor(200, 200, 200);
        doc.line(14, headerBottom, 196, headerBottom);

        // --- Report Meta ---
        const infoStartY = 65;
        const dateFormatted = format(new Date(), "dd MMM yyyy, HH:mm");

        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(80, 80, 80);
        doc.text("Report Details:", 14, infoStartY);

        doc.setFont("helvetica", "normal");
        doc.text(`Generated On: ${dateFormatted}`, 14, infoStartY + 6);
        doc.text(`Total Parties: ${data.length}`, 14, infoStartY + 11);

        // --- Table ---
        const tableRows = data.map(party => [
            sanitizeText(party.name),
            party.totalSales > 0 ? formatCurrencySafe(party.totalSales) : "-",
            party.totalPurchases > 0 ? formatCurrencySafe(party.totalPurchases) : "-",
            formatCurrencySafe(party.netBalance)
        ]);

        autoTable(doc, {
            startY: 85,
            head: [["Party Name", "Total Sales", "Total Purchases", "Net Balance"]],
            body: tableRows,
            theme: 'striped',
            headStyles: {
                fillColor: [37, 99, 235],
                textColor: 255,
                fontStyle: 'bold'
            },
            columnStyles: {
                0: { cellWidth: 72 }, // Name
                1: { cellWidth: 35, halign: 'right' }, // Sales
                2: { cellWidth: 35, halign: 'right' }, // Purchases
                3: { cellWidth: 40, halign: 'right' }  // Net Balance
            },
            styles: {
                font: "helvetica",
                fontSize: 9,
                cellPadding: 4,
                overflow: 'linebreak'
            },
            margin: { top: 70, left: 14, right: 14 },
            didParseCell: (hookData) => {
                if (hookData.section === 'head') {
                    if (hookData.column.index > 0) {
                        hookData.cell.styles.halign = 'right';
                    }
                }
            }
        });

        // --- Footer ---
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.setFont("helvetica", "italic");
        doc.text("Generated by FinFlow Business Tracker", 105, 280, { align: "center" });

        // Save
        doc.save(`Party_Report_${format(new Date(), "yyyy-MM-dd_HHmm")}.pdf`);

    } catch (e) {
        console.error("PDF generation failed", e);
        alert("Failed to generate PDF. Please try again.");
    }
};
