/**
 * Auto-generated TypeScript definitions from FastAPI OpenAPI Schema.
 * Generated by @rupaybill/api-types pipeline.
 * DO NOT EDIT DIRECTLY.
 */

export interface AgingBucket {
  /** Bucket 0 30 */
  bucket_0_30: number;
  /** Bucket 31 60 */
  bucket_31_60: number;
  /** Bucket 61 90 */
  bucket_61_90: number;
  /** Bucket 90 Plus */
  bucket_90_plus: number;
  /** Contact Phone */
  contact_phone?: string | null;
  /** Party Id */
  party_id?: string | null;
  /** Party Name */
  party_name: string;
  /** Total Outstanding */
  total_outstanding: number;
}

export interface AiMessage {
  /** Content */
  content: string | any[];
  /** Role */
  role: "system" | "user" | "assistant";
}

export interface AuditLogItem {
  /** Action */
  action: string;
  /** Created At */
  created_at: string;
  /** Id */
  id: string;
  /** Metadata */
  metadata?: Record<string, any>;
  /** Resource Id */
  resource_id?: string | null;
  /** Resource Type */
  resource_type: string;
  /** Store Id */
  store_id: string;
  /** User Id */
  user_id?: string | null;
}

export interface AuditLogListResponse {
  /** Logs */
  logs: AuditLogItem[];
  /** Total */
  total: number;
}

export interface BalanceSheetRequest {
  /** Borrowed */
  borrowed?: Record<string, any>[];
  /** Expenses */
  expenses?: Record<string, any>[];
  /** Lent */
  lent?: Record<string, any>[];
  /** Parties */
  parties?: Record<string, any>[];
  /** Products */
  products?: Record<string, any>[];
  /** Purchases */
  purchases?: Record<string, any>[];
  /** Sales */
  sales?: Record<string, any>[];
}

export interface BalanceSheetResponse {
  /** Current Assets */
  current_assets?: Record<string, number>;
  /** Current Liabilities */
  current_liabilities?: Record<string, number>;
  /** Current Period Profit */
  current_period_profit: number;
  /** Is Balanced */
  is_balanced: boolean;
  /** Non Current Assets */
  non_current_assets?: Record<string, number>;
  /** Non Current Liabilities */
  non_current_liabilities?: Record<string, number>;
  /** Proprietor Capital */
  proprietor_capital: number;
  /** Total Assets */
  total_assets: number;
  /** Total Current Assets */
  total_current_assets: number;
  /** Total Current Liabilities */
  total_current_liabilities: number;
  /** Total Equity */
  total_equity: number;
  /** Total Liabilities */
  total_liabilities: number;
  /** Total Liabilities And Equity */
  total_liabilities_and_equity: number;
  /** Total Non Current Assets */
  total_non_current_assets: number;
}

export interface BarcodeBulkGenerateRequest {
  /** Barcode Type */
  barcode_type?: string;
  /** Prefix */
  prefix?: string | null;
  /** Product Ids */
  product_ids?: string[] | null;
}

export interface BarcodeGenerateRequest {
  /** Barcode Type */
  barcode_type?: string;
  /** Prefix */
  prefix?: string | null;
  /** Product Id */
  product_id?: string | null;
}

export interface BarcodeValidateRequest {
  /** Barcode */
  barcode: string;
  /** Barcode Type */
  barcode_type?: string;
  /** Product Id */
  product_id?: string | null;
}

export interface BillItem {
  /** Name */
  name: string;
  /** Price */
  price?: number | null;
  /** Quantity */
  quantity?: number | null;
}

export interface BusinessInsightRequest {
  /** Borrowed */
  borrowed?: Record<string, any>[];
  /** Currency */
  currency?: string;
  /** Expenses */
  expenses?: Record<string, any>[];
  /** Lent */
  lent?: Record<string, any>[];
  /** Onlinestore */
  onlineStore?: Record<string, any>[] | null;
  /** Products */
  products?: Record<string, any>[];
  /** Purchases */
  purchases?: Record<string, any>[];
  /** Sales */
  sales?: Record<string, any>[];
}

export interface BusinessInsightResponse {
  /** Confidencescore */
  confidenceScore: string;
  /** Debtanalysis */
  debtAnalysis: string;
  /** Financialimpact */
  financialImpact: string;
  /** Headline */
  headline: string;
  /** Predictedoutcome */
  predictedOutcome: string;
  /** Suggestions */
  suggestions: string[];
  /** Summary */
  summary: string;
  /** Taxanalysis */
  taxAnalysis: string;
}

export interface CashFlowStatementRequest {
  /** Borrowed */
  borrowed?: Record<string, any>[];
  /** Expenses */
  expenses?: Record<string, any>[];
  /** Lent */
  lent?: Record<string, any>[];
  /** Purchases */
  purchases?: Record<string, any>[];
  /** Sales */
  sales?: Record<string, any>[];
}

export interface CashFlowStatementResponse {
  /** Closing Cash And Bank Estimate */
  closing_cash_and_bank_estimate: number;
  /** Financing Inflows */
  financing_inflows: number;
  /** Financing Outflows */
  financing_outflows: number;
  /** Net Cash Generated */
  net_cash_generated: number;
  /** Net Financing Cash Flow */
  net_financing_cash_flow: number;
  /** Net Operating Cash Flow */
  net_operating_cash_flow: number;
  /** Operating Inflows */
  operating_inflows: number;
  /** Operating Outflows */
  operating_outflows: number;
}

export interface CategoryRecord {
  /** Id */
  id: string;
  /** Name */
  name: string;
}

export interface CompletionRequest {
  /** Maxoutputtokens */
  maxOutputTokens?: number | null;
  /** Messages */
  messages: AiMessage[];
  /** Model */
  model?: string | null;
  /** Response Format */
  response_format?: Record<string, any> | null;
  /** Stream */
  stream?: boolean | null;
  /** Temperature */
  temperature?: number | null;
}

export interface FeatureRequestCreate {
  /** Description */
  description: string;
  /** Title */
  title: string;
}

export interface FeatureRequestResponse {
  /** Description */
  description: string;
  /** Id */
  id: string;
  /** Notes */
  notes?: string | null;
  /** Status */
  status: string;
  /** Submitted At */
  submitted_at: string;
  /** Title */
  title: string;
  /** Updated At */
  updated_at: string;
  /** User Email */
  user_email?: string | null;
  /** User Id */
  user_id?: string | null;
}

export interface FeatureRequestUpdate {
  /** Notes */
  notes?: string | null;
  /** Status */
  status: string;
}

export interface FinanceInsightRequest {
  /** Borrowed */
  borrowed?: Record<string, any>[] | null;
  /** Categories */
  categories?: CategoryRecord[];
  /** Currency */
  currency?: string;
  /** Expenses */
  expenses?: Record<string, any>[];
  /** Lent */
  lent?: Record<string, any>[] | null;
  /** Lowstockcount */
  lowStockCount?: number | null;
  /** Mode */
  mode: "dashboard" | "explain-expenses" | "losing-money" | "tax-summary" | "spending-prediction";
  /** Sales */
  sales?: Record<string, any>[] | null;
}

export interface FinanceInsightResponse {
  /** Confidencescore */
  confidenceScore: string;
  /** Financialimpact */
  financialImpact: string;
  /** Headline */
  headline: string;
  /** Predictedoutcome */
  predictedOutcome: string;
  /** Predictions */
  predictions: string[];
  /** Risks */
  risks: string[];
  /** Suggestedaction */
  suggestedAction: string;
  /** Summary */
  summary: string;
  /** Topcategories */
  topCategories: Record<string, any>[];
}

export interface FinancialSummaryRequest {
  /** Borrowed */
  borrowed?: Record<string, any>[];
  /** Currency */
  currency?: string;
  /** Expenses */
  expenses?: Record<string, any>[];
  /** Lent */
  lent?: Record<string, any>[];
  /** Products */
  products?: Record<string, any>[];
  /** Purchases */
  purchases?: Record<string, any>[];
  /** Sales */
  sales?: Record<string, any>[];
}

export interface FinancialSummaryResponse {
  /** Currency */
  currency: string;
  /** Gross Margin Pct */
  gross_margin_pct: number;
  /** Gross Profit */
  gross_profit: number;
  /** Net Debt Position */
  net_debt_position: number;
  /** Net Profit */
  net_profit: number;
  /** Net Profit Margin Pct */
  net_profit_margin_pct: number;
  /** Operating Cash Flow Estimate */
  operating_cash_flow_estimate: number;
  /** Total Cost Of Goods */
  total_cost_of_goods: number;
  /** Total Operating Expenses */
  total_operating_expenses: number;
  /** Total Payables */
  total_payables: number;
  /** Total Receivables */
  total_receivables: number;
  /** Total Sales Revenue */
  total_sales_revenue: number;
}

export interface GSTR1B2BRecord {
  /** Customer Gstin */
  customer_gstin: string;
  /** Customer Name */
  customer_name: string;
  /** Invoice Date */
  invoice_date: string;
  /** Invoice Number */
  invoice_number: string;
  /** Invoice Value */
  invoice_value: number;
  /** Items */
  items?: GSTR1InvoiceItem[];
  /** Place Of Supply */
  place_of_supply: string;
  /** Reverse Charge */
  reverse_charge?: string;
}

export interface GSTR1B2CSRecord {
  /** Cgst Amount */
  cgst_amount: number;
  /** Igst Amount */
  igst_amount: number;
  /** Place Of Supply */
  place_of_supply: string;
  /** Rate */
  rate: number;
  /** Sgst Amount */
  sgst_amount: number;
  /** Taxable Value */
  taxable_value: number;
  /** Total Amount */
  total_amount: number;
}

export interface GSTR1HSNRecord {
  /** Cgst Amount */
  cgst_amount: number;
  /** Description */
  description: string;
  /** Hsn Code */
  hsn_code: string;
  /** Igst Amount */
  igst_amount: number;
  /** Sgst Amount */
  sgst_amount: number;
  /** Taxable Value */
  taxable_value: number;
  /** Total Quantity */
  total_quantity: number;
  /** Total Value */
  total_value: number;
  /** Uqc */
  uqc?: string;
}

export interface GSTR1InvoiceItem {
  /** Cgst Amount */
  cgst_amount: number;
  /** Igst Amount */
  igst_amount: number;
  /** Rate */
  rate: number;
  /** Sgst Amount */
  sgst_amount: number;
  /** Taxable Value */
  taxable_value: number;
  /** Total Amount */
  total_amount: number;
}

export interface GSTR1ReportRequest {
  /** Merchant Gstin */
  merchant_gstin?: string | null;
  /** Month */
  month?: string | null;
  /** Parties */
  parties?: Record<string, any>[];
  /** Sales */
  sales?: Record<string, any>[];
  /** Year */
  year?: number | null;
}

export interface GSTR1ReportResponse {
  /** B2B */
  b2b?: GSTR1B2BRecord[];
  /** B2Cs */
  b2cs?: GSTR1B2CSRecord[];
  /** Gstin */
  gstin?: string | null;
  /** Hsn Summary */
  hsn_summary?: GSTR1HSNRecord[];
  /** Period */
  period?: string | null;
  /** Total Cgst */
  total_cgst: number;
  /** Total Igst */
  total_igst: number;
  /** Total Invoices */
  total_invoices: number;
  /** Total Sgst */
  total_sgst: number;
  /** Total Tax Liability */
  total_tax_liability: number;
  /** Total Taxable Value */
  total_taxable_value: number;
}

export interface GSTR2BRecord {
  /** Cgst Amount */
  cgst_amount: number;
  /** Igst Amount */
  igst_amount: number;
  /** Invoice Date */
  invoice_date: string;
  /** Invoice Number */
  invoice_number: string;
  /** Invoice Value */
  invoice_value: number;
  /** Itc Available */
  itc_available?: string;
  /** Sgst Amount */
  sgst_amount: number;
  /** Supplier Gstin */
  supplier_gstin: string;
  /** Supplier Name */
  supplier_name: string;
  /** Taxable Value */
  taxable_value: number;
}

export interface GSTR2BReportRequest {
  /** Merchant Gstin */
  merchant_gstin?: string | null;
  /** Period */
  period?: string | null;
  /** Purchases */
  purchases?: Record<string, any>[];
}

export interface GSTR2BReportResponse {
  /** Gstin */
  gstin?: string | null;
  /** Period */
  period?: string | null;
  /** Records */
  records?: GSTR2BRecord[];
  /** Total Bills */
  total_bills: number;
  /** Total Cgst */
  total_cgst: number;
  /** Total Igst */
  total_igst: number;
  /** Total Itc Available */
  total_itc_available: number;
  /** Total Sgst */
  total_sgst: number;
  /** Total Taxable Value */
  total_taxable_value: number;
}

export interface GSTR3BReportRequest {
  /** Merchant Gstin */
  merchant_gstin?: string | null;
  /** Period */
  period?: string | null;
  /** Purchases */
  purchases?: Record<string, any>[];
  /** Sales */
  sales?: Record<string, any>[];
}

export interface GSTR3BSummaryResponse {
  /** Eligible Itc Cgst */
  eligible_itc_cgst: number;
  /** Eligible Itc Igst */
  eligible_itc_igst: number;
  /** Eligible Itc Sgst */
  eligible_itc_sgst: number;
  /** Eligible Itc Total */
  eligible_itc_total: number;
  /** Gstin */
  gstin?: string | null;
  /** Net Tax Payable Cgst */
  net_tax_payable_cgst: number;
  /** Net Tax Payable Igst */
  net_tax_payable_igst: number;
  /** Net Tax Payable Sgst */
  net_tax_payable_sgst: number;
  /** Net Tax Payable Total */
  net_tax_payable_total: number;
  /** Outward Cgst */
  outward_cgst: number;
  /** Outward Igst */
  outward_igst: number;
  /** Outward Sgst */
  outward_sgst: number;
  /** Outward Taxable Value */
  outward_taxable_value: number;
  /** Outward Total Tax */
  outward_total_tax: number;
  /** Period */
  period?: string | null;
}

export interface GSTR9AnnualReportResponse {
  /** Financial Year */
  financial_year: string;
  /** Gstin */
  gstin?: string | null;
  /** Net Tax Paid Or Payable */
  net_tax_paid_or_payable: number;
  /** Total B2B Sales */
  total_b2b_sales: number;
  /** Total B2C Sales */
  total_b2c_sales: number;
  /** Total Inward Purchases */
  total_inward_purchases: number;
  /** Total Itc Availed */
  total_itc_availed: number;
  /** Total Output Tax */
  total_output_tax: number;
  /** Total Outward Turnover */
  total_outward_turnover: number;
}

export interface GSTR9ReportRequest {
  /** Financial Year */
  financial_year?: string;
  /** Merchant Gstin */
  merchant_gstin?: string | null;
  /** Purchases */
  purchases?: Record<string, any>[];
  /** Sales */
  sales?: Record<string, any>[];
}

export interface HTTPValidationError {
  /** Detail */
  detail?: ValidationError[];
}

export interface InventoryAdjustmentRequest {
  /** Adjustment Type */
  adjustment_type: string;
  /** Notes */
  notes?: string | null;
  /** Product Id */
  product_id: string;
  /** Quantity */
  quantity: number;
}

export interface InventoryValuationSummary {
  /** Low Stock Count */
  low_stock_count: number;
  /** Total Cost Value */
  total_cost_value: number;
  /** Total Products */
  total_products: number;
  /** Total Retail Value */
  total_retail_value: number;
  /** Total Stock Units */
  total_stock_units: number;
}

export interface InvoiceCreateRequest {
  /** Amount Paid */
  amount_paid?: number;
  /** Billing Address */
  billing_address?: string | null;
  /** Custom Invoice Number */
  custom_invoice_number?: string | null;
  /** Customer Email */
  customer_email?: string | null;
  /** Customer Gstin */
  customer_gstin?: string | null;
  /** Customer Name */
  customer_name?: string | null;
  /** Customer Phone */
  customer_phone?: string | null;
  /** Date */
  date?: string | null;
  /** Document Type */
  document_type?: string;
  /** Due Date */
  due_date?: string | null;
  /** Invoice Number Prefix */
  invoice_number_prefix?: string | null;
  /** Is Item Wise Tax */
  is_item_wise_tax?: boolean;
  /** Items */
  items: InvoiceItemInput[];
  /** Notes */
  notes?: string | null;
  /** Overall Discount */
  overall_discount?: number;
  /** Party Id */
  party_id?: string | null;
  /** Payment Method */
  payment_method?: string | null;
  /** Place Of Supply */
  place_of_supply?: string | null;
  /** Round Off */
  round_off?: boolean;
  /** Shipping Address */
  shipping_address?: string | null;
  /** Status */
  status?: string;
  /** Tax Rate */
  tax_rate?: number;
}

export interface InvoiceItemInput {
  /** Description */
  description?: string | null;
  /** Discount */
  discount?: number;
  /** Hsn Code */
  hsn_code?: string | null;
  /** Id */
  id?: string | null;
  /** Name */
  name?: string | null;
  /** Price */
  price?: number;
  /** Product Id */
  product_id?: string | null;
  /** Quantity */
  quantity?: number;
  /** Tax Rate */
  tax_rate?: number | null;
  /** Unit */
  unit?: string | null;
}

export interface InvoiceUpdateRequest {
  /** Amount Paid */
  amount_paid?: number | null;
  /** Customer Email */
  customer_email?: string | null;
  /** Customer Gstin */
  customer_gstin?: string | null;
  /** Customer Name */
  customer_name?: string | null;
  /** Customer Phone */
  customer_phone?: string | null;
  /** Due Date */
  due_date?: string | null;
  /** Notes */
  notes?: string | null;
  /** Payment Method */
  payment_method?: string | null;
  /** Place Of Supply */
  place_of_supply?: string | null;
  /** Status */
  status?: string | null;
}

export interface MagicAddEntry {
  /** Amount */
  amount: number;
  /** Category */
  category: string;
  /** Date */
  date: string;
  /** Description */
  description: string;
  /** Due Date */
  due_date?: string | null;
  /** Person Name */
  person_name?: string | null;
  /** Type */
  type: "expense" | "income" | "lent" | "borrowed" | "transfer";
}

export interface MagicAddParseRequest {
  /** Current Date */
  current_date?: string | null;
  /** Text */
  text: string;
}

export interface MagicAddParseResponse {
  /** Entries */
  entries: MagicAddEntry[];
  /** Summary */
  summary: string;
}

export interface OrderCancel {
  /** Customerphone */
  customerPhone?: string | null;
  /** Orderid */
  orderId: string;
}

export interface OrderCreate {
  /** Amount */
  amount?: number | null;
  /** Currency */
  currency?: string;
  /** Customername */
  customerName?: string | null;
  /** Customerphone */
  customerPhone?: string | null;
  /** Idempotencykey */
  idempotencyKey?: string | null;
  /** Orderid */
  orderId?: string | null;
  /** Receipt */
  receipt?: string | null;
}

export interface POSCashMovementRequest {
  /** Amount */
  amount: number;
  /** Reason */
  reason: string;
  /** Shift Id */
  shift_id: string;
  /** Type */
  type: string;
}

export interface POSReturnItemSchema {
  /** Original Sale Item Id */
  original_sale_item_id?: string | null;
  /** Product Id */
  product_id?: string | null;
  /** Product Name */
  product_name: string;
  /** Quantity returned */
  quantity: number;
  /** Restock Inventory */
  restock_inventory?: boolean;
  /** Tax Rate */
  tax_rate?: number;
  /** Original unit selling price */
  unit_price: number;
}

export interface POSReturnRequest {
  /** Reason */
  reason: string;
  /** Refund Method */
  refund_method?: string;
  /** Return Items */
  return_items: POSReturnItemSchema[];
  /** Sale Id */
  sale_id: string;
  /** Shift Id */
  shift_id?: string | null;
}

export interface POSSaleCreateRequest {
  /** Amount Paid */
  amount_paid?: number;
  /** Customer Name */
  customer_name?: string | null;
  /** Customer Phone */
  customer_phone?: string | null;
  /** Discount Amount */
  discount_amount?: number;
  /** Idempotency Key */
  idempotency_key?: string | null;
  /** Is Offline Sync */
  is_offline_sync?: boolean;
  /** Items */
  items: POSSaleItemSchema[];
  /** Notes */
  notes?: string | null;
  /** Offline Invoice Number */
  offline_invoice_number?: string | null;
  /** Party Id */
  party_id?: string | null;
  /** Payment Method */
  payment_method?: string;
  /** Shift Id */
  shift_id?: string | null;
  /** Terminal Id */
  terminal_id?: string | null;
}

export interface POSSaleItemSchema {
  /** Description */
  description?: string | null;
  /** Line discount percentage */
  discount?: number;
  /** Hsn Code */
  hsn_code?: string | null;
  /** Id */
  id?: string | null;
  /** Name */
  name: string;
  /** Selling unit price */
  price: number;
  /** Product Id */
  product_id?: string | null;
  /** Quantity sold, supports decimals */
  quantity: number;
  /** GST / Tax percentage */
  tax_rate?: number;
  /** Unit */
  unit?: string | null;
}

export interface POSShiftCloseRequest {
  /** Actual Cash */
  actual_cash: number;
  /** Notes */
  notes?: string | null;
}

export interface POSShiftOpenRequest {
  /** Notes */
  notes?: string | null;
  /** Opening Cash */
  opening_cash?: number;
  /** Terminal Id */
  terminal_id?: string | null;
}

export interface PartyCreateRequest {
  /** Address */
  address?: string | null;
  /** Email */
  email?: string | null;
  /** Gst Number */
  gst_number?: string | null;
  /** Name */
  name: string;
  /** Notes */
  notes?: string | null;
  /** Opening Balance */
  opening_balance?: number;
  /** Opening Balance Type */
  opening_balance_type?: string;
  /** Phone */
  phone?: string | null;
  /** Type */
  type?: string;
}

export interface PartyUpdateRequest {
  /** Address */
  address?: string | null;
  /** Email */
  email?: string | null;
  /** Gst Number */
  gst_number?: string | null;
  /** Name */
  name?: string | null;
  /** Notes */
  notes?: string | null;
  /** Opening Balance */
  opening_balance?: number | null;
  /** Opening Balance Type */
  opening_balance_type?: string | null;
  /** Phone */
  phone?: string | null;
  /** Type */
  type?: string | null;
}

export interface PaymentRefund {
  /** Amount */
  amount?: number | null;
  /** Paymentid */
  paymentId: string;
  /** Reason */
  reason?: string | null;
}

export interface PaymentVerify {
  /** Billingcycle */
  billingCycle?: string | null;
  /** Gatewayorderid */
  gatewayOrderId?: string | null;
  /** Gatewaypaymentid */
  gatewayPaymentId?: string | null;
  /** Gatewaysignature */
  gatewaySignature?: string | null;
  /** Order Id */
  order_id?: string | null;
  /** Payment Id */
  payment_id?: string | null;
  /** Planid */
  planId?: string | null;
  /** Razorpay Order Id */
  razorpay_order_id?: string | null;
  /** Razorpay Payment Id */
  razorpay_payment_id?: string | null;
  /** Razorpay Signature */
  razorpay_signature?: string | null;
  /** Signature */
  signature?: string | null;
}

export interface ProductContentRequest {
  /** Costprice */
  costPrice?: number | null;
  /** Name */
  name: string;
  /** Price */
  price: number;
  /** Stockquantity */
  stockQuantity?: number | null;
  /** Unit */
  unit?: string | null;
}

export interface ProductContentResponse {
  /** Description */
  description: string;
  /** Highlights */
  highlights: string[];
  /** Marketingcopy */
  marketingCopy: string;
  /** Seodescription */
  seoDescription: string;
  /** Seotitle */
  seoTitle: string;
  /** Title */
  title: string;
}

export interface ProductSearchRequest {
  /** Products */
  products?: Record<string, any>[];
  /** Query */
  query: string;
}

export interface ProductSearchResponse {
  /** Categories */
  categories: string[];
  /** Explanation */
  explanation: string;
  /** Intent */
  intent: string;
  /** Keywords */
  keywords: string[];
  /** Maxprice */
  maxPrice?: number | null;
  /** Minprice */
  minPrice?: number | null;
  /** Rankedproductids */
  rankedProductIds: string[];
}

export interface ProfitAndLossRequest {
  /** Direct Expense Categories */
  direct_expense_categories?: string[] | null;
  /** Expenses */
  expenses?: Record<string, any>[];
  /** Products */
  products?: Record<string, any>[];
  /** Purchases */
  purchases?: Record<string, any>[];
  /** Sales */
  sales?: Record<string, any>[];
}

export interface ProfitAndLossResponse {
  /** Closing Stock Value */
  closing_stock_value: number;
  /** Cost Of Goods Sold */
  cost_of_goods_sold: number;
  /** Direct Expenses */
  direct_expenses: number;
  /** Gross Profit */
  gross_profit: number;
  /** Gross Profit Margin Pct */
  gross_profit_margin_pct: number;
  /** Indirect Expenses */
  indirect_expenses?: Record<string, number>;
  /** Net Profit Before Tax */
  net_profit_before_tax: number;
  /** Net Profit Margin Pct */
  net_profit_margin_pct: number;
  /** Net Revenue */
  net_revenue: number;
  /** Opening Stock Value */
  opening_stock_value: number;
  /** Purchases Cost */
  purchases_cost: number;
  /** Revenue From Operations */
  revenue_from_operations: number;
  /** Sales Returns */
  sales_returns: number;
  /** Total Indirect Expenses */
  total_indirect_expenses: number;
}

export interface PurchaseCreateRequest {
  /** Amount Paid */
  amount_paid?: number;
  /** Attachment Url */
  attachment_url?: string | null;
  /** Bill Number */
  bill_number?: string | null;
  /** Date */
  date?: string | null;
  /** Discount Amount */
  discount_amount?: number;
  /** Due Date */
  due_date?: string | null;
  /** Items */
  items: PurchaseItemInput[];
  /** Notes */
  notes?: string | null;
  /** Party Id */
  party_id?: string | null;
  /** Place Of Supply */
  place_of_supply?: string | null;
  /** Status */
  status?: string;
  /** Tax Rate */
  tax_rate?: number;
  /** Vendor Email */
  vendor_email?: string | null;
  /** Vendor Gstin */
  vendor_gstin?: string | null;
  /** Vendor Name */
  vendor_name: string;
  /** Vendor Phone */
  vendor_phone?: string | null;
}

export interface PurchaseItemInput {
  /** Description */
  description?: string | null;
  /** Discount */
  discount?: number;
  /** Id */
  id?: string | null;
  /** Name */
  name?: string | null;
  /** Price */
  price?: number;
  /** Product Id */
  product_id?: string | null;
  /** Quantity */
  quantity?: number;
  /** Tax Rate */
  tax_rate?: number | null;
  /** Unit */
  unit?: string | null;
}

export interface ReceivablesAgingRequest {
  /** Ref Date */
  ref_date?: string | null;
  /** Sales */
  sales?: Record<string, any>[];
}

export interface ReceivablesAgingResponse {
  /** Buckets */
  buckets?: AgingBucket[];
  /** Total 0 30 */
  total_0_30: number;
  /** Total 31 60 */
  total_31_60: number;
  /** Total 61 90 */
  total_61_90: number;
  /** Total 90 Plus */
  total_90_plus: number;
  /** Total Outstanding */
  total_outstanding: number;
}

export interface SalesSettingsUpdateRequest {
  /** Autosendwhatsapponinvoice */
  autoSendWhatsAppOnInvoice?: boolean | null;
  /** Backdatinglimitdays */
  backdatingLimitDays?: number | null;
  /** Confirmbeforedelete */
  confirmBeforeDelete?: boolean | null;
  /** Defaultpaymenttermsdays */
  defaultPaymentTermsDays?: number | null;
  /** Defaultstatus */
  defaultStatus?: string | null;
  /** Defaulttaxrate */
  defaultTaxRate?: number | null;
  /** Defaulttermsandconditions */
  defaultTermsAndConditions?: string | null;
  /** Enablehsncode */
  enableHsnCode?: boolean | null;
  /** Enableitemwisetax */
  enableItemWiseTax?: boolean | null;
  /** Enablequickbilling */
  enableQuickBilling?: boolean | null;
  /** Gstmode */
  gstMode?: string | null;
  /** Invoicenumberprefix */
  invoiceNumberPrefix?: string | null;
  /** Preventbackdating */
  preventBackdating?: boolean | null;
  /** Roundofftotal */
  roundOffTotal?: boolean | null;
  /** Showitemtaxrateonbill */
  showItemTaxRateOnBill?: boolean | null;
  /** Show Party Pending Balance */
  show_party_pending_balance?: boolean | null;
  /** Show Party Previous Balance */
  show_party_previous_balance?: boolean | null;
  /** Warnonoutstandingbalance */
  warnOnOutstandingBalance?: boolean | null;
}

export interface ScanBillData {
  /** Bill Date */
  bill_date?: string | null;
  /** Category Suggestion */
  category_suggestion?: string | null;
  /** Items */
  items?: BillItem[] | null;
  /** Merchant Name */
  merchant_name?: string | null;
  /** Payment Method */
  payment_method?: string | null;
  /** Tax Amount */
  tax_amount?: number | null;
  /** Total Amount */
  total_amount?: number | null;
}

export interface ScanBillRequest {
  /** Imagebase64 */
  imageBase64: string;
  /** Mimetype */
  mimeType?: string;
}

export interface ScanBillResponse {
  data: ScanBillData;
  /** Success */
  success?: boolean;
}

export interface SmartExpenseParseRequest {
  /** Current Date */
  current_date?: string | null;
  /** Text */
  text: string;
}

export interface SmartExpenseParseResponse {
  /** Amount */
  amount: number;
  /** Category */
  category: string;
  /** Confidence */
  confidence?: number;
  /** Date */
  date: string;
  /** Description */
  description: string;
  /** Merchant */
  merchant?: string | null;
  /** Payment Mode */
  payment_mode?: string | null;
}

export interface SubscriptionOrderCreate {
  /** Billingcycle */
  billingCycle: "monthly" | "annual";
  /** Couponcode */
  couponCode?: string | null;
  /** Customername */
  customerName?: string | null;
  /** Customerphone */
  customerPhone?: string | null;
  /** Idempotencykey */
  idempotencyKey?: string | null;
  /** Planid */
  planId: "starter" | "pro" | "business" | "premium";
}

export interface TrialBalanceItem {
  /** Account Name */
  account_name: string;
  /** Account Type */
  account_type: string;
  /** Credit Amount */
  credit_amount: number;
  /** Debit Amount */
  debit_amount: number;
}

export interface TrialBalanceRequest {
  /** Borrowed */
  borrowed?: Record<string, any>[];
  /** Expenses */
  expenses?: Record<string, any>[];
  /** Lent */
  lent?: Record<string, any>[];
  /** Parties */
  parties?: Record<string, any>[];
  /** Products */
  products?: Record<string, any>[];
  /** Purchases */
  purchases?: Record<string, any>[];
  /** Sales */
  sales?: Record<string, any>[];
}

export interface TrialBalanceResponse {
  /** Difference */
  difference: number;
  /** Is Balanced */
  is_balanced: boolean;
  /** Items */
  items?: TrialBalanceItem[];
  /** Total Credit */
  total_credit: number;
  /** Total Debit */
  total_debit: number;
}

export interface ValidationError {
  /** Context */
  ctx?: Record<string, any>;
  /** Input */
  input?: any;
  /** Location */
  loc: (string | number)[];
  /** Message */
  msg: string;
  /** Error Type */
  type: string;
}

export interface WhatsAppConnectionResponse {
  /** Created At */
  created_at?: string | null;
  /** Display Name */
  display_name?: string | null;
  /** Error Message */
  error_message?: string | null;
  /** Id */
  id?: string | null;
  /** Last Connected At */
  last_connected_at?: string | null;
  /** Last Seen At */
  last_seen_at?: string | null;
  /** Phone Number */
  phone_number?: string | null;
  /** Provider */
  provider?: string;
  /** Provider Session Id */
  provider_session_id: string;
  /** Qr Code Data */
  qr_code_data?: string | null;
  /** Status */
  status?: string;
  /** Store Id */
  store_id: string;
  /** Updated At */
  updated_at?: string | null;
}

export interface WhatsAppDisconnectResponse {
  /** Message */
  message: string;
  /** Status */
  status: string;
  /** Success */
  success: boolean;
}

export interface WhatsAppQRCodeResponse {
  /** Message */
  message?: string | null;
  /** Qr Code */
  qr_code?: string | null;
  /** Status */
  status: string;
}

export interface WhatsAppSendInvoiceRequest {
  /** Amount Paid */
  amount_paid?: number;
  /** Balance Due */
  balance_due?: number;
  /** Currency Symbol */
  currency_symbol?: string;
  /** Custom Notes */
  custom_notes?: string | null;
  /** Customer Name */
  customer_name: string;
  /** Customer Phone */
  customer_phone: string;
  /** Document Base64 */
  document_base64?: string | null;
  /** Document Filename */
  document_filename?: string | null;
  /** Due Date */
  due_date?: string | null;
  /** Force Resend */
  force_resend?: boolean;
  /** Idempotency Key */
  idempotency_key?: string | null;
  /** Invoice Id */
  invoice_id?: string | null;
  /** Invoice Number */
  invoice_number: string;
  /** Total Amount */
  total_amount: number;
}

export interface WhatsAppSendMessageRequest {
  /** Customer Name */
  customer_name?: string | null;
  /** Document Base64 */
  document_base64?: string | null;
  /** Document Filename */
  document_filename?: string | null;
  /** Force Resend */
  force_resend?: boolean;
  /** Idempotency Key */
  idempotency_key?: string | null;
  /** Message */
  message: string;
  /** Message Type */
  message_type?: string;
  /** Phone Number */
  phone_number: string;
}

export interface WhatsAppSendReceiptRequest {
  /** Amount Received */
  amount_received: number;
  /** Currency Symbol */
  currency_symbol?: string;
  /** Custom Notes */
  custom_notes?: string | null;
  /** Customer Name */
  customer_name: string;
  /** Customer Phone */
  customer_phone: string;
  /** Document Base64 */
  document_base64?: string | null;
  /** Document Filename */
  document_filename?: string | null;
  /** Force Resend */
  force_resend?: boolean;
  /** Idempotency Key */
  idempotency_key?: string | null;
  /** Invoice Number */
  invoice_number?: string | null;
  /** Payment Id */
  payment_id?: string | null;
  /** Payment Method */
  payment_method?: string;
  /** Receipt Number */
  receipt_number: string;
  /** Remaining Balance */
  remaining_balance?: number;
}

export interface WhatsAppSendReminderRequest {
  /** Currency Symbol */
  currency_symbol?: string;
  /** Custom Notes */
  custom_notes?: string | null;
  /** Customer Name */
  customer_name: string;
  /** Customer Phone */
  customer_phone: string;
  /** Due Date */
  due_date?: string | null;
  /** Force Resend */
  force_resend?: boolean;
  /** Idempotency Key */
  idempotency_key?: string | null;
  /** Invoice Number */
  invoice_number?: string | null;
  /** Outstanding Amount */
  outstanding_amount: number;
  /** Party Id */
  party_id?: string | null;
}

export interface WhatsAppSendResponse {
  /** Detail */
  detail?: string | null;
  /** Is Duplicate */
  is_duplicate?: boolean;
  /** Message Id */
  message_id?: string | null;
  /** Phone Number */
  phone_number: string;
  /** Status */
  status: string;
  /** Success */
  success: boolean;
}

export interface WhatsAppTestMessageRequest {
  /** Message */
  message?: string | null;
  /** Phone Number */
  phone_number: string;
}
