// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/core/integrations/supabase/types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL) {
  throw new Error("Missing VITE_SUPABASE_URL");
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Missing VITE_SUPABASE_PUBLISHABLE_KEY");
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      // Keep the user logged in after closing/reopening browser
      persistSession: true,

      // IMPORTANT:
      // localStorage persists between browser sessions.
      // sessionStorage does NOT.
      storage: window.localStorage,

      // Automatically refresh expired access tokens
      autoRefreshToken: true,

      // Handle auth redirects
      detectSessionInUrl: true,
    },
  }
);